# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"P": "discrete.ipynb",
         "V": "discrete.ipynb",
         "DiscretePrior": "discrete.ipynb",
         "Variables": "discrete.ipynb",
         "DiscreteKey": "discrete.ipynb",
         "show": "display.ipynb",
         "pretty": "display.ipynb"}

modules = ["discrete.py",
           "display.py"]

doc_url = "https://dellaert.github.io/gtbook/"

git_url = "https://github.com/dellaert/gtbook/tree/master/"

def custom_doc_links(name): return None
