# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rename": "cli.ipynb",
         "fix_colab_links": "cli.ipynb",
         "REGEX": "cli.ipynb",
         "fix_nbs_colab_links": "cli.ipynb",
         "dbs_position": "dbn.ipynb",
         "dbk_position": "dbn.ipynb",
         "dbc_position": "dbn.ipynb",
         "dbn_positions": "dbn.ipynb",
         "dbn_writer": "dbn.ipynb",
         "Variables": "discrete.ipynb",
         "DiscreteKey": "discrete.ipynb",
         "show": "display.ipynb",
         "pretty": "display.ipynb",
         "randomImages": "display.ipynb",
         "ROBOTS": "display.ipynb"}

modules = ["cli.py",
           "dbn.py",
           "discrete.py",
           "display.py"]

doc_url = "https://gtbook.github.io//gtbook/"

git_url = "https://github.com/gtbook/gtbook/tree/master/"

def custom_doc_links(name): return None
