# AUTOGENERATED! DO NOT EDIT! File to edit: cli.ipynb (unless otherwise specified).

__all__ = ['rename', 'add_copyright']

# Cell
from fastcore.script import call_parse

# Cell
@call_parse
def rename():
    """Rename notebooks to base 1 for chapters."""
    print("Renaming notebooks now.")


# Cell
@call_parse
def add_copyright():
    """Add copyright string to all specified files."""
    print("Addding copyright string.")
