# AUTOGENERATED! DO NOT EDIT! File to edit: ../vacuum.ipynb.

# %% auto 0
__all__ = ['rooms', 'action_space', 'action_spec', 'light_levels', 'sensor_spec']

# %% ../vacuum.ipynb 3
#| export

# %% ../vacuum.ipynb 5
rooms = ["Living Room", "Kitchen", "Office", "Hallway", "Dining Room"]

# %% ../vacuum.ipynb 8
action_space = ["L", "R", "U", "D"]
action_spec = """
    1/0/0/0/0 2/8/0/0/0 1/0/0/0/0 2/0/0/8/0
    8/2/0/0/0 0/1/0/0/0 0/1/0/0/0 0/2/0/0/8
    0/0/1/0/0 0/0/2/8/0 0/0/1/0/0 0/0/1/0/0
    0/0/8/2/0 0/0/0/2/8 8/0/0/2/0 0/0/0/1/0
    0/0/0/8/2 0/0/0/0/1 0/8/0/0/2 0/0/0/0/1
    """

# %% ../vacuum.ipynb 13
light_levels = ["dark", "medium", "light"]
sensor_spec = "1/1/8 1/1/8 2/7/1 8/1/1 1/8/1"
